### ISSUE TITLE
Expected a string but was BEGIN_OBJECT at line 9 column 14 path $.data.from

### ISSUE THREAD

**Issue by Izimbergenov** [team-telnyx/telnyx-java#1]
![Screenshot_1](https://user-images.githubusercontent.com/7349114/86622101-222ad280-bfe1-11ea-9df8-b11be50cf773.png)

I wrote code from sample. But got:
 com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 9 column 14 path $.data.from
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at io.swagger.client.JSON.deserialize(JSON.java:134)
	at io.swagger.client.ApiClient.deserialize(ApiClient.java:710)
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:913)
	at io.swagger.client.ApiClient.execute(ApiClient.java:840)
	at io.swagger.client.api.MessagesApi.createMessageWithHttpInfo(MessagesApi.java:266)
	at io.swagger.client.api.MessagesApi.createMessage(MessagesApi.java:252)

Anyway sms was delivered

**Comment by Izimbergenov** [comment]
Now works
