### ISSUE TITLE
MessageApi

### ISSUE THREAD

**Issue by ShiXiaoXiang2019** [team-telnyx/telnyx-java#45]
createLongCodeMessage    toNumber  +12015558888    An error will be reported when a long code text message is sent to this number

Error reading entity from input stream.

javax.ws.rs.ProcessingException: Error reading entity from input stream.
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:900) ~[jersey-common-2.32.jar!/:na]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:845) ~[jersey-common-2.32.jar!/:na]
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:340) ~[jersey-client-2.32.jar!/:na]
	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:104) ~[jersey-client-2.32.jar!/:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.32.jar!/:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.32.jar!/:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205) ~[jersey-common-2.32.jar!/:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365) ~[jersey-common-2.32.jar!/:na]
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:244) ~[jersey-client-2.32.jar!/:na]
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:101) ~[jersey-client-2.32.jar!/:na]
	at com.telnyx.sdk.ApiClient.deserialize(ApiClient.java:788) ~[telnyx-2.8.0.jar!/:na]
	at com.telnyx.sdk.ApiClient.invokeAPI(ApiClient.java:959) ~[telnyx-2.8.0.jar!/:na]
	at com.telnyx.sdk.api.MessagesApi.createLongCodeMessageWithHttpInfo(MessagesApi.java:114) ~[telnyx-2.8.0.jar!/:na]
	at com.telnyx.sdk.api.MessagesApi.createLongCodeMessage(MessagesApi.java:68) ~[telnyx-2.8.0.jar!/:na]
	at com.tongsoft.voice.common.utils.telnyx.TelnyxCallUtil.sendMessage(TelnyxCallUtil.java:64) ~[classes!/:0.0.1-SNAPSHOT]
	at com.tongsoft.voice.service.common.impl.AsyncServiceImpl.sendTelnyxMessage(AsyncServiceImpl.java:93) [classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_281]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) [spring-aop-5.3.3.jar!/:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) [spring-aop-5.3.3.jar!/:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.3.3.jar!/:5.3.3]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) [spring-aop-5.3.3.jar!/:5.3.3]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_281]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_281]
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.telnyx.sdk.model.OutboundMessagePayloadTo$LineTypeEnum`, problem: Unexpected value 'Unknown'
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 19, column: 22] (through reference chain: com.telnyx.sdk.model.MessageResponse["data"]->com.telnyx.sdk.model.OutboundMessagePayload["to"]->java.util.ArrayList[0]->com.telnyx.sdk.model.OutboundMessagePayloadTo["line_type"])
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1758) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1128) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:159) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:290) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2042) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1201) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:837) ~[jersey-media-json-jackson-2.32.jar!/:na]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233) ~[jersey-common-2.32.jar!/:na]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212) ~[jersey-common-2.32.jar!/:na]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132) ~[jersey-common-2.32.jar!/:na]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072) ~[jersey-common-2.32.jar!/:na]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:885) ~[jersey-common-2.32.jar!/:na]
	... 27 common frames omitted
Caused by: java.lang.IllegalArgumentException: Unexpected value 'Unknown'
	at com.telnyx.sdk.model.OutboundMessagePayloadTo$LineTypeEnum.fromValue(OutboundMessagePayloadTo.java:137) ~[telnyx-2.8.0.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_281]
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.callOnWith(AnnotatedMethod.java:115) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:151) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	... 47 common frames omitted

**Comment by ShiXiaoXiang2019** [comment]
> 我在接收带有 Unknown 的 webhook 时遇到了这个问题`line_type`，我通过自己手动反序列化有效负载并忽略 SDK 模型来“修复”了这个问题。但是，我注意到在使用`createMessage`.

**Comment by ShiXiaoXiang2019** [comment]
> I was running into this problem when receiving webhooks with the Unknown `line_type`, which I "fixed" by manually deserializing the payload myself and ignoring the SDK models. However, I noticed that I get a similar error when using `createMessage`.

The parameters in the webhook don't matter. I just parse JSON directly, but there are problems with the SDK that can't be solved. I can only send requests using HTTP. Their developers may be very few and don't have time to solve these problems
